config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "admin/base#admin_login"
  get 'welcome/index'

  post '/wx_payment', to: 'weixin#wx_verify'

  namespace :admin do
    #root "wx_menus#index"
    root "base#admin_login"
    get 'home' => 'base#home'
    get 'index' => 'admin#index' 
    post 'do_login' => 'admin#do_login'
    delete 'do_logout' => 'admin#do_logout' 

    resources :admin

    resources :ad_images do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :products do
      resources :product_images do
        collection do
          post :file_upload
          put :file_upload
          patch :file_upload
          put :up_serial
          put :down_serial
        end
        member do
          put :disable
          put :enable
        end
      end

      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :shops do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :tags do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :users
  end

  resources :applets, only: [:index, :show] do
    collection do
      get  :cart
      get  :cart_show
      post :check_order_status
      post :cancel_order
      post :create_order
      get  :crm_info
      post :delete_user_address
      get  :home_show
      get  :login
      get  :load_address_list
      get  :load_address_info
      get  :load_customer_info
      get  :product_show
      post :save_address
      post :save_user_info
      get  :set_phone
      get  :shops_list
      get  :user_info
    end
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  scope :active, -> { where(active: true).order(:position) }

  def up_serial(target_id)
    self.class.transaction do
      pre_item = self.class.find(target_id)
      index = pre_item.position
      self.class.where(admin_id: self.admin_id, product_id: self.product_id).where.not(id: self.id).where('`position` <= ? AND `position` >= ?', self.position, pre_item.position).update_all('`position` = `position` + 1')
      self.update(:position => index)
    end
  end

  def down_serial(target_id)
    self.class.transaction do
      next_item = self.class.find(target_id)
      index = next_item.position
      self.class.where(admin_id: self.admin_id, product_id: self.product_id).where.not(id: self.id).where('`position` >= ? AND `position` <= ?', self.position, next_item.position).update_all('`position` = `position` - 1')
      self.update(:position => index)
    end
  end

  def enable
    self.update(active: true)
  end

  def disable
    self.update(active: false)
  end
end

app/controllers/admin/product_images_controller.rb
class Admin::ProductImagesController < Admin::BaseController
  before_action :reload_product
  layout 'admin'

  def index
    @items = @product.product_images.order('active desc,position')
  end

  def new
    @item = @product.product_images.build
  end

  def create
    @item = @product.product_images.build(product_image_params)
    if @item.save
      redirect_to admin_product_product_images_path(@product)
    else
      render :new
    end
  end

  def update
    @item = @product.product_set_images.find(params[:id])
    if @item.update_attributes(product_image_params)
      redirect_to admin_product_product_images_path(@product)
    else
      render :edit
    end
  end

  def edit
    @item = @product.product_images.find(params[:id])
  end

  def destroy
    @item = @product.product_images.find(params[:id])
    @item.destroy
    redirect_to :back
  end

  def file_upload
    file_upload_to_qiniu('product_image')
  end

  def up_serial
    item = ProductImage.where(id: params[:id]).first
    if item.up_serial params[:target_id]
      render js: "alert('操作成功');"
    else
      render js: "alert('操作失败');"
    end
  end

  def down_serial
    item = ProductImage.where(id: params[:id]).first
    if item.down_serial params[:target_id]
      render js: "alert('操作成功');"
    else
      render js: "alert('操作失败');"
    end
  end

  def enable
    item = ProductImage.find(params[:id])
    if item.enable
      redirect_to admin_product_product_images_path(@product), alert: '成功'
    else
      redirect_to admin_product_product_images_path(@product), alert: '失败'
    end
  end

  def disable
    item = ProductImage.find(params[:id])
    if item.disable
      redirect_to admin_product_product_images_path(@product), alert: '成功'
    else
      redirect_to admin_product_product_images_path(@product), alert: '失败'
    end
  end

  private

  def reload_product
    @product = Product.find(params[:product_id])
  end

  def product_image_params
    params.require(:product_image).permit!
  end
end

app/views/admin/product_images/_form.haml
.col-md-6
  = form_for @item, url: url do |f|
    - if @item.errors.any?
      .form-group
        %ul
          - @item.errors.messages.each do |key,msg|
            %li= msg.join(',')
    .form-group
      = f.label "位置"
      %br
      = f.text_field :position, class: 'form-control', type: :number

    .form-group
      = f.label "是否启用"
      = f.select :active, options_for_select({'是' => true, '否' => false}, @item.active), {}, class: 'form-control'

    = f.text_field :mobile_image, style: 'display: none'
    = render partial: 'upload_image', locals: {item: @item, image_name: 'mobile_image', image_size: '宽带为750', button_name: 'mobile-image', input_name: 'product_image_mobile_image', upload_url: file_upload_admin_product_product_images_path(type: 'mobile')}

    = f.submit '保存', class: 'btn btn-success'

app/views/admin/product_images/edit.haml
%h3 修改产品详细图片
= link_to '返回', admin_product_product_images_path(@product), class: 'btn btn-success'

= render partial: 'form', locals: {url: admin_product_product_image_path(@product, @item)}

app/views/admin/product_images/index.haml
%h3 产品详细图片列表
= link_to '返回', admin_products_path, class: "btn btn-secondary"
= link_to '新建产品图片', new_admin_product_product_image_path(@product), class: "btn btn-success"


%table.table.table-striped
  %tr
    %th 图片
    %th 是否显示
    %th 操作

  %tbody(ondragstart="dragEnterHandler(event)" ondragover="dragOverHandler(event)" ondragend="dragEndHandler(event)")
    - @items.each do |item|
      - @draggable = true
      %tr(id="product-image-#{item.id}" draggable='true' data-id= "#{item.id}" data-up_url= "#{up_serial_admin_product_product_images_path(:id =>item.id)}" data-down_url= "#{down_serial_admin_product_product_images_path(:id =>item.id)}")
        %td= image_tag item.mobile_image, style: 'width: 100px'
        %td= active_chinese_name(item)
        %td
          = link_to '修改', edit_admin_product_product_image_path(@product, item)
          |
          - if item.active
            = link_to '关闭', disable_admin_product_product_image_path(@product,item), :method => :put
          - else
            = link_to '启用', enable_admin_product_product_image_path(@product,item), :method => :put
          |
          = link_to '删除', admin_product_product_image_path(@product, item), method: :delete, data: { :confirm => '确定删除吗？' }

app/views/admin/product_images/new.haml
%h3 新建产品详细图片

= link_to '返回', admin_product_product_images_path(@product), class: 'btn btn-success'

= render :partial => 'form', :locals => {url: admin_product_product_images_path(@product)}