config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "admin/base#admin_login"
  get 'welcome/index'

  post '/wx_payment', to: 'weixin#wx_verify'

  namespace :admin do
    #root "wx_menus#index"
    root "base#admin_login"
    get 'home' => 'base#home'
    get 'index' => 'admin#index' 
    post 'do_login' => 'admin#do_login'
    delete 'do_logout' => 'admin#do_logout' 

    resources :admin

    resources :ad_images do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :products do
      resources :product_images do
        collection do
          post :file_upload
          put :file_upload
          patch :file_upload
          put :up_serial
          put :down_serial
        end
        member do
          put :disable
          put :enable
        end
      end

      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :shops do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :tags do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :users
  end

  resources :applets, only: [:index, :show] do
    collection do
      get  :cart
      get  :cart_show
      post :check_order_status
      post :cancel_order
      post :create_order
      get  :crm_info
      post :delete_user_address
      get  :home_show
      get  :login
      get  :load_address_list
      get  :load_address_info
      get  :load_customer_info
      get  :product_show
      post :save_address
      post :save_user_info
      get  :set_phone
      get  :shops_list
      get  :user_info
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :role_assignments
  has_many :roles, through: :role_assignments
  has_many :products
  has_many :shops
  has_many :tags

  # PASSWORD
  attr_accessor :password_confirmation

  def is?(role)
    return true if self.roles.where(name: role).first
    false
  end

  Role.all.each do |role|
    define_method "#{role.name}?" do
      self.is?(role.name)
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :admin
  scope :active, -> { where(active: true).order(:position) }

  def up_serial(target_id)
    self.class.transaction do
      pre_item = self.class.find(target_id)
      index = pre_item.position
      self.class.where(admin_id: self.admin_id).where.not(id: self.id).where('`position` <= ? AND `position` >= ?', self.position, pre_item.position).update_all('`position` = `position` + 1')
      self.update(:position => index)
    end
  end

  def down_serial(target_id)
    self.class.transaction do
      next_item = self.class.find(target_id)
      index = next_item.position
      self.class.where(admin_id: self.admin_id).where.not(id: self.id).where('`position` >= ? AND `position` <= ?', self.position, next_item.position).update_all('`position` = `position` - 1')
      self.update(:position => index)
    end
  end

  def enable
    self.update(active: true)
  end

  def disable
    self.update(active: false)
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  layout 'admin'

  def index
    @params = params[:q] || {}
    @q = @admin.tags.order('active desc, position asc').ransack(@params)
    @items = @q.result(distinct: true).page(params[:page])
  end

  def new
    @item = @admin.tags.build
    @current_products = @item.products
  end
  def create
    @item = @admin.tags.build(current_record_params)
    @current_products = @item.products
    if @item.save
      redirect_to admin_tags_path
    else
      render :new
    end
  end

  def update
    @item = Tag.find(params[:id])
    @current_products = @item.products
    p current_record_params
    if @item.update_attributes(current_record_params)
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  def edit
    @item = Tag.find(params[:id])
    @current_products = @item.products
  end

  def destroy
    @item = Tag.find(params[:id])
    redirect_to admin_tags_path if @item.destroy
  end

  def up_serial
    item = Tag.where(id: params[:id]).first
    if item.up_serial params[:target_id]
      render js: "alert('操作成功');"
    else
      render js: "alert('操作失败');"
    end
  end

  def down_serial
    item = Tag.where(id: params[:id]).first
    if item.down_serial params[:target_id]
      render js: "alert('操作成功');"
    else
      render js: "alert('操作失败');"
    end
  end

  def enable
    item = Tag.find(params[:id])
    if item.enable
      redirect_to admin_products_path, alert: '成功'
    else
      redirect_to admin_products_path, alert: '失败'
    end
  end

  def disable
    item = Tag.find(params[:id])
    if item.disable
      redirect_to admin_products_path, alert: '成功'
    else
      redirect_to admin_products_path, alert: '失败'
    end
  end

  private

  def current_record_params
    params.require(:tag).permit!
  end 
end

app/views/admin/tags/_form.haml
- if false
  .col-md-6
    = simple_form_for(@item, url: url) do |f|
      - if @item.errors.any?
        .form-group
          %ul
            - @item.errors.messages.each do |key,msg|
              %li= msg.join(',')

      .form-group
        = f.input :title, label: "名称"

      .form-group
        = f.association :products, as: :check_boxes, label: "产品", label_method: :title
      .form-group
        = f.input :active, as: :boolean, label: "是否售卖"

      = f.button :submit, value: "保存", class: "btn btn-success"
- else

  .col-md-6
    = form_for @item, url: url do |f|
      - if @item.errors.any?
        .form-group
          %ul
            - @item.errors.messages.each do |key,msg|
              %li= msg.join(',')
      .form-group
        = f.label "名称"
        = f.text_field :title, class: 'form-control'

      .form-group
        = f.label "包含产品"
      .form-group
        - @admin.products.each do |product|
          = check_box_tag 'tag[product_ids][]', product.id, @current_products.include?(product)
          %span= product.title
          

      .form-group
        = f.label "是否启用"
        = f.select :active, options_for_select({'是' => true, '否' => false}, @item.active), {}, class: 'form-control'

      = f.submit '保存', class: 'btn btn-success'

app/views/admin/tags/edit.haml
%h3 修改标签

= link_to '返回', admin_tags_path, class: "btn btn-secondary"

= render partial: 'form', locals: {url: admin_tag_path(@item)}

app/views/admin/tags/index.haml
%h2 标签列表
= search_form_for @q, url: admin_tags_path, html: {class: 'form-inline'} do |f|
  .form-group
    = f.search_field :title_cont, class: "form-control", placeholder: "名称"
  = f.submit '查询', class: "btn btn-secondary"
  = link_to '新建标签', new_admin_tag_path, class: "btn btn-success"

%br
%div
  总数： 
  = @items.total_count
.table-responsive
  %table.table.table-striped.table-sm
    %thead
      %tr
        %th 名称
        %th 是否启用
        %th 操作
    %tbody(ondragstart="dragEnterHandler(event)" ondragover="dragOverHandler(event)" ondragend="dragEndHandler(event)")
      - @items.each do |item|
        - @draggable = true
        %tr(id="product-image-#{item.id}" draggable='true' data-id= "#{item.id}" data-up_url= "#{up_serial_admin_tags_path(:id =>item.id)}" data-down_url= "#{down_serial_admin_tags_path(:id =>item.id)}")
          %td= item.title
          %td= active_chinese_name(item)
          %td
            = link_to '修改', edit_admin_tag_path(item)
            |
            - if item.active
              = link_to '关闭', disable_admin_tag_path(item), :method => :put
            - else
              = link_to '启用', enable_admin_tag_path(item), :method => :put
            = link_to '删除', admin_tag_path(item), :method => :delete, :data => { :confirm => '确定删除?' }
  = paginate @items

app/views/admin/tags/new.haml
%h3 新建标签

= render partial: 'form', locals: {url: admin_tags_path}