config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "admin/base#admin_login"
  get 'welcome/index'

  post '/wx_payment', to: 'weixin#wx_verify'

  namespace :admin do
    #root "wx_menus#index"
    root "base#admin_login"
    get 'home' => 'base#home'
    get 'index' => 'admin#index' 
    post 'do_login' => 'admin#do_login'
    delete 'do_logout' => 'admin#do_logout' 

    resources :admin

    resources :ad_images do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :products do
      resources :product_images do
        collection do
          post :file_upload
          put :file_upload
          patch :file_upload
          put :up_serial
          put :down_serial
        end
        member do
          put :disable
          put :enable
        end
      end

      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :shops do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :tags do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :users
  end

  resources :applets, only: [:index, :show] do
    collection do
      get  :cart
      get  :cart_show
      post :check_order_status
      post :cancel_order
      post :create_order
      get  :crm_info
      post :delete_user_address
      get  :home_show
      get  :login
      get  :load_address_list
      get  :load_address_info
      get  :load_customer_info
      get  :product_show
      post :save_address
      post :save_user_info
      get  :set_phone
      get  :shops_list
      get  :user_info
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :admin
  has_many :product_images
  scope :active, -> { where(active: true).order(:position) }

  def up_serial(target_id)
    self.class.transaction do
      pre_item = self.class.find(target_id)
      index = pre_item.position
      self.class.where(admin_id: self.admin_id).where.not(id: self.id).where('`position` <= ? AND `position` >= ?', self.position, pre_item.position).update_all('`position` = `position` + 1')
      self.update(:position => index)
    end
  end

  def down_serial(target_id)
    self.class.transaction do
      next_item = self.class.find(target_id)
      index = next_item.position
      self.class.where(admin_id: self.admin_id).where.not(id: self.id).where('`position` >= ? AND `position` <= ?', self.position, next_item.position).update_all('`position` = `position` - 1')
      self.update(:position => index)
    end
  end

  def enable
    self.update(active: true)
  end

  def disable
    self.update(active: false)
  end

  def to_applet_show
    attrs = {
      id: self.id,
      title: self.title,
      min_count: self.min_count,
      desc: self.description,
      price: self.price,
      city_name: self.city_name,
      start_date: self.start_date,
      end_date: self.end_date,
      img_url: self.detailed_image
    }
    if self.type == 'Course'
      info_extend = CourseExtend.find_by_course_id(self.id)
      attrs[:address] = info_extend.try(:address)
      attrs[:teachers] = self.teachers.map{|item| item.to_course_list}
    end

    attrs[:exprie_product] = true unless self.active
    attrs[:product_images] = self.product_images.active.pluck(:mobile_image)
    attrs
  end

  def to_applet_cart_show
    attrs = {
      id: self.id,
      title: self.title,
      price: self.price,
      min_count: self.min_count,
      img_url: self.detailed_image
    }
    attrs
  end

  def to_applet_list
    {
      id: self.id,
      title: self.title,
      price: self.price,
      min_count: self.min_count,
      img_url: self.front_image
    }
  end

  def self.get_product_list_hash(product_ids)
    products =  Product.where(id: product_ids)
    item_hash = {}
    products.each do |product|
      item_hash[product.id] = product.to_applet_list
    end
    return item_hash
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  layout 'admin'

  def index
    @params = params[:q] || {}
    @q = @admin.products.order('active desc, position asc').ransack(@params)
    @items = @q.result(distinct: true).page(params[:page])
  end

  def new
    @item = @admin.products.build
  end
  def create
    @item = @admin.products.build(current_record_params)
    if @item.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
    @item = Product.find(params[:id])
    if @item.update_attributes(current_record_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def edit
    @item = Product.find(params[:id])
  end


  def file_upload
    file_upload_to_qiniu('product')
  end

  def up_serial
    item = Product.where(id: params[:id]).first
    if item.up_serial params[:target_id]
      render js: "alert('操作成功');"
    else
      render js: "alert('操作失败');"
    end
  end

  def down_serial
    item = Product.where(id: params[:id]).first
    if item.down_serial params[:target_id]
      render js: "alert('操作成功');"
    else
      render js: "alert('操作失败');"
    end
  end

  def enable
    item = Product.find(params[:id])
    if item.enable
      redirect_to admin_products_path, alert: '成功'
    else
      redirect_to admin_products_path, alert: '失败'
    end
  end

  def disable
    item = Product.find(params[:id])
    if item.disable
      redirect_to admin_products_path, alert: '成功'
    else
      redirect_to admin_products_path, alert: '失败'
    end
  end

  private

  def current_record_params
    params.require(:product).permit!
  end 
end

app/views/admin/products/_form.haml
.col-md-6
  = form_for @item, url: url do |f|
    - if @item.errors.any?
      .form-group
        %ul
          - @item.errors.messages.each do |key,msg|
            %li= msg.join(',')
    .form-group
      = f.label "*名称"
      %br
      = f.text_field :title, class: 'form-control'

    .form-group
      = f.label "价格"
      %br
      = f.text_field :price, class: 'form-control'

    .form-group
      = f.label "最小购买数量"
      %br
      = f.text_field :min_count, class: 'form-control'

    .form-group
      = f.label "描述"
      %br
      = f.text_area :description, class: 'form-control'

    .form-group
      = f.label "是否启用"
      = f.select :active, options_for_select({'是' => true, '否' => false}, @item.active), {}, class: 'form-control'

    = f.text_field :front_image, style: 'display: none'
    = render partial: 'upload_image', locals: {item: @item, image_name: 'front_image', image_size: '首页图片(220x220)', button_name: 'front-image', input_name: 'product_front_image', upload_url: file_upload_admin_products_path(type: 'front')}

    = f.text_field :detailed_image, style: 'display: none'
    = render partial: 'upload_image', locals: {item: @item, image_name: 'detailed_image', image_size: '详细页图片(750x360)', button_name: 'detailed-image', input_name: 'product_detailed_image', upload_url: file_upload_admin_products_path(type: 'detailed')}

    = f.submit '保存', class: 'btn btn-success'

app/views/admin/products/edit.haml
%h3 修改产品

= link_to '返回', admin_products_path, class: "btn btn-secondary"

= render partial: 'form', locals: {url: admin_product_path(@item)}

app/views/admin/products/index.haml
%h2 产品列表
= search_form_for @q, url: admin_products_path, html: {class: 'form-inline'} do |f|
  .form-group
    = f.search_field :title_cont, class: "form-control", placeholder: "名称"
  = f.submit '查询', class: "btn btn-secondary"
  = link_to '新建产品', new_admin_product_path, class: "btn btn-success"

%br
%div
  总数： 
  = @items.total_count
.table-responsive
  %table.table.table-striped.table-sm
    %thead
      %tr
        %th 产品sku
        %th 名称
        %th 价格
        %th 最小购买数量
        %th 首页图片
        %th 详细页图片
        %th 是否启用
        %th 操作
    %tbody(ondragstart="dragEnterHandler(event)" ondragover="dragOverHandler(event)" ondragend="dragEndHandler(event)")
      - @items.each do |item|
        - @draggable = true
        %tr(id="item-#{item.id}" draggable='true' data-id= "#{item.id}" data-up_url= "#{up_serial_admin_products_path(:id =>item.id)}" data-down_url= "#{down_serial_admin_products_path(:id =>item.id)}")
          %td= item.id
          %td= item.title
          %td= item.price
          %td= item.min_count
          %td= image_tag(item.front_image || '', width: '100px')
          %td= image_tag(item.detailed_image || '', width: '100px')
          %td= active_chinese_name(item)
          %td
            = link_to '修改', edit_admin_product_path(item)
            |
            - if item.active
              = link_to '关闭', disable_admin_product_path(item), :method => :put
            - else
              = link_to '启用', enable_admin_product_path(item), :method => :put
            |
            = link_to "详情图片", admin_product_product_images_path(item)
  = paginate @items

app/views/admin/products/new.haml
%h3 新建产品

= render partial: 'form', locals: {url: admin_products_path}