config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "admin/base#admin_login"
  get 'welcome/index'

  post '/wx_payment', to: 'weixin#wx_verify'

  namespace :admin do
    #root "wx_menus#index"
    root "base#admin_login"
    get 'home' => 'base#home'
    get 'index' => 'admin#index' 
    post 'do_login' => 'admin#do_login'
    delete 'do_logout' => 'admin#do_logout' 

    resources :admin

    resources :ad_images do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :products do
      resources :product_images do
        collection do
          post :file_upload
          put :file_upload
          patch :file_upload
          put :up_serial
          put :down_serial
        end
        member do
          put :disable
          put :enable
        end
      end

      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :shops do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
      end
    end

    resources :tags do
      collection do
        post :file_upload
        put :file_upload
        patch :file_upload
        put :up_serial
        put :down_serial
      end
      member do
        put :disable
        put :enable
      end
    end

    resources :users
  end

  resources :applets, only: [:index, :show] do
    collection do
      get  :cart
      get  :cart_show
      post :check_order_status
      post :cancel_order
      post :create_order
      get  :crm_info
      post :delete_user_address
      get  :home_show
      get  :login
      get  :load_address_list
      get  :load_address_info
      get  :load_customer_info
      get  :product_show
      post :save_address
      post :save_user_info
      get  :set_phone
      get  :shops_list
      get  :user_info
    end
  end
end

app/views/layouts/admin.haml
!!!
%html{lang: "zh-CN"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "text/html; charset=utf-8", "http-equiv" => "content-type"}/
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title 小家订购管理后台
    %meta{content: "", name: "description"}/
    %meta{content: "width=device-width", name: "viewport"}/
    = stylesheet_link_tag    "admin", media: "all"
    = javascript_include_tag "admin"
    = csrf_meta_tags

  %body{role: 'document', style: 'align-items: normal;'}
    %nav.navbar.navbar-dark.fixed-top.bg-dark.flex-md-nowrap.p-0.shadow
      %a.navbar-brand.col-sm-3.col-md-2.mr-0{href: "#"} 小家订购
      - if false
        %input.form-control.form-control-dark.w-100{type: 'text', placeholder: "Search", "aria-label" => "Search"}
      %ul.navbar-nav.px-3
        %li.nav-item.text-nowrap.white-color
          = @admin.try(:user_name)
          |
          = link_to '退出', admin_do_logout_path, method: :delete, class: "white-color"
          - if @admin.present?
            |
            = link_to '修改密码', edit_admin_admin_path(@admin), class: "white-color"

    %div{style: 'height: 50px;'}
    .container-fluid
      %nav.col-md-2.d-none.d-md-block.bg-light.sidebar
        .sidebar-sticky
          %ul.nav.flex-column
            - if false
              %li.nav-item
                %a.nav-link
                  //%span.fa.fa-user-o
                  用户信息
            %li.nav-item
              = link_to '图片信息', admin_ad_images_path, class: "nav-link #{'active' if params[:controller] == 'admin/ad_images'}"
            %li.nav-item
              = link_to '微信群', admin_shops_path, class: "nav-link #{'active' if params[:controller] == 'admin/shops'}"
            %li.nav-item
              = link_to '标签', admin_tags_path, class: "nav-link #{'active' if params[:controller] == 'admin/tags'}"
            %li.nav-item
              = link_to '产品', admin_products_path, class: "nav-link #{'active' if params[:controller] == 'admin/products'}"
            %li.nav-item
              = link_to '用户信息', admin_users_path, class: "nav-link #{'active' if params[:controller] == 'admin/users'}"
      .col-md-12.ml-sm-auto.col-lg-10.px-4{role: 'main'}
        = yield
    %footer#footer

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>小家订购</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>